<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/SN_web_lightmode.png" width="300"> 
</center>

<h1>Web scrape a Global Bike-Sharing Systems Wiki Page</h1>

Estimated time needed: **20** minutes

## Lab Overview:

Before getting your hands dirty on the actual data analysis tasks, you first need to obtain some background and context information about well-known bike sharing systems worldwide, such as their location, launch date, rental bike size, and so on.

You can get such information from this Wiki page: 

https://en.wikipedia.org/wiki/List_of_bicycle-sharing_systems

<a href="https://cognitiveclass.ai/">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/l2-list-bike-sharing-systems.png" width="600" align="center">
</a>

First import necessary libraries for the webscraping task.


In this lab, you need to use the `rvest` library to obtain the bike sharing systems table from the above web page, convert the table into a data frame, and write the data frame to a csv file for future data wrangling and analysis tasks.

In [1]:
# Check if need to install rvest` library
require("rvest")

library(rvest)

Loading required package: rvest

# TASK: Extract bike sharing systems HTML table from a Wiki page and convert it into a data frame

_TODO:_ Get the root HTML node

In [3]:
url <- "https://en.wikipedia.org/wiki/List_of_bicycle-sharing_systems"
# Get the root HTML node by calling the `read_html()` method with URL
# Get the root HTML node
root_html <- read_html(url)

root_html

{html_document}
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" lang="en" dir="ltr">
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body class="skin--responsive skin-vector skin-vector-search-vue mediawik ...

Note that this HTML page at least contains three child `<table>` nodes under the root HTML node. So, you will need to use `html_nodes(root_node, "table")` function to get all its child `<table>` nodes:

```
<html>
  <table>(table1)</table>
  <table>(table2)</table>
  <table>(table3)</table>
  ...
</html>
```

table_nodes <- html_nodes(root_node, "table")

You can use a `for` loop to print each table, and then you will see that the actual the bike sharing table is the first element `table_nodes[[1]]`.

Next, you need to convert this HTML table into a data frame using the `html_table()` function. You may choose to include `fill = TRUE` argument to fill any empty table rows/columns.

In [4]:
# Convert the bike-sharing system table into a dataframe
# Convert the bike-sharing system table into a dataframe
bike_sharing <- html_table(root_html, fill = TRUE)

# View the dataframe
bike_sharing

[[1]]
# A tibble: 898 × 8
   Country   Country `City / Region` Name  System Operator Launched Discontinued
   <chr>     <chr>   <chr>           <chr> <chr>  <chr>    <chr>    <chr>
 1 Albania   Albania Tirana[5]       Ecov… ""     ""       March 2… "Discontinu…
 2 Argentina Argent… Buenos Aires[6… Ecob… "Sert… "Bike I… 2010     ""
 3 Argentina Argent… Mendoza[10]     Metr… ""     ""       2014     ""
 4 Argentina Argent… Rosario         Mi B… ""     ""       2 Decem… ""
 5 Argentina Argent… San Lorenzo, S… Bici… "Bici… ""       27 Nove… ""
 6 Australia Austra… Melbourne[12]   Melb… "PBSC… "Motiva… June 20… "30 Novembe…
 7 Australia Austra… Melbourne[12]   oBike "4 Ge… ""       July 20… "July 2018"
 8 Australia Austra… Brisbane[14][1… City… "3 Ge… "JCDeca… Septemb… "July 2021[…
 9 Australia Austra… Sydney          Redd… "Redd… ""       July 20… ""
10 Australia Austra… Sydney          oBike "4 Ge… ""       July 20… "July 2018"
# ℹ 888 more rows

[[2]]
# A tibble: 16 × 12
   .mw-parser-output .nav…¹ .mw-parser-output .n…² ``    ``    ``    ``    ``
   <chr>                    <chr>                  <chr> <chr> <chr> <chr> <chr>
 1 List of bicycle-sharing… "List of bicycle-shar… NA     NA   NA     NA   NA
 2 Asia                     "East Asia\nCityBike … East… "Cit… Sout… "Any… Sout…
 3 East Asia                "CityBike (Kaohsiung,… NA     NA   NA     NA   NA
 4 Southeast Asia           "Anywheel (Singapore)… NA     NA   NA     NA   NA
 5 South Asia               "JoBike (Bangladesh)\… NA     NA   NA     NA   NA
 6 West Asia                "Antbis (Antalya)\nBd… NA     NA   NA     NA   NA
 7 Central Asia             "Astana Bike (Astana,… NA     NA   NA     NA   NA
 8 Europe                   "in multiple countrie… NA     NA   NA     NA   NA
 9 North America            "Canada\nàVélo (Quebe… Cana… "àVé… Mexi… "Eco… Unit…
10 Canada                   "àVélo (Quebec City)\… NA     NA   NA     NA   NA
11 Mexico                   "EcoBici (Mexico City… NA     NA   NA     NA   NA
12 United States            "B-Cycle: Austin B-Cy… NA     NA   NA     NA   NA
13 Oceania                  "Airbike\nLime (Austr… NA     NA   NA     NA   NA
14 South America            "Bike Rio (Rio de Jan… NA     NA   NA     NA   NA
15 Companies                "BCycle\nBolt\nDeutsc… NA     NA   NA     NA   NA
16 Defunct                  "8D Technologies\nBal… NA     NA   NA     NA   NA
# ℹ abbreviated names:
#   ¹​`.mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}html.skin-theme-clientpref-night .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}@media(prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}}@media print{.mw-parser-output .navbar{display:none!important}}vteBicycle-sharing systems`,
#   ²​`.mw-parser-output .navbar{display:inline;font-size:88%;font-weight:normal}.mw-parser-output .navbar-collapse{float:left;text-align:left}.mw-parser-output .navbar-boxtext{word-spacing:0}.mw-parser-output .navbar ul{display:inline-block;white-space:nowrap;line-height:inherit}.mw-parser-output .navbar-brackets::before{margin-right:-0.125em;content:"[ "}.mw-parser-output .navbar-brackets::after{margin-left:-0.125em;content:" ]"}.mw-parser-output .navbar li{word-spacing:-0.125em}.mw-parser-output .navbar a>span,.mw-parser-output .navbar a>abbr{text-decoration:inherit}.mw-parser-output .navbar-mini abbr{font-variant:small-caps;border-bottom:none;text-decoration:none;cursor:inherit}.mw-parser-output .navbar-ct-full{font-size:114%;margin:0 7em}.mw-parser-output .navbar-ct-mini{font-size:114%;margin:0 4em}html.skin-theme-clientpref-night .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}@media(prefers-color-scheme:dark){html.skin-theme-clientpref-os .mw-parser-output .navbar li a abbr{color:var(--color-base)!important}}@media print{.mw-parser-output .navbar{display:none!important}}vteBicycle-sharing systems`
# ℹ 5 more variables: `` <chr>, `` <chr>, `` <chr>, `` <chr>, `` <chr>

[[3]]
# A tibble: 5 × 2
  X1             X2
  <chr>          <chr>
1 East Asia      "CityBike (Kaohsiung, Taiwan)\nDdareungi (Seoul, South Korea)\…
2 Southeast Asia "Anywheel (Singapore)\nLinkBike (George Town, Penang, Malaysia…
3 South Asia     "JoBike (Bangladesh)\nTiruchirappalli Bicycle Share (India)"
4 West Asia      "Antbis (Antalya)\nBdood (Tehran, Shiraz)\nBisim (İzmir)\nCyac…
5 Central Asia   "Astana Bike (Astana, Kazakhstan)"

[[4]]
# A tibble: 3 × 2
  X1            X2
  <chr>         <chr>
1 Canada        "àVélo (Quebec City)\nBike Share Toronto\nBIXI Montréal\nVeloGo…
2 Mexico        "EcoBici (Mexico City)\nMi Bici (Guadalajara)"
3 United States "B-Cycle: Austin B-Cycle\nAventura B-Cycle\nBattle Creek B-Cycl…

Summarize the bike sharing system data frame

In [5]:
# Summarize the dataframe
summary(bike_sharing)

     Length Class  Mode
[1,]  8     tbl_df list
[2,] 12     tbl_df list
[3,]  2     tbl_df list
[4,]  2     tbl_df list

Export the data frame as a csv file called `raw_bike_sharing_systems.csv`

In [21]:
# Export the dataframe into a csv file
write.csv(bike_sharing, "bike_sharing.csv", row.names = FALSE)

For more details about webscraping with `rvest`, please refer to the previous webscraping notebook here:

[Webscraping in R](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M4_Working_With_Data/lab3_jupyter_webscraping.ipynb)

## Authors

<a href="https://www.linkedin.com/in/yan-luo-96288783/" target="_blank">Yan Luo</a>

### Other Contributors

<!-- ## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description           |
| ----------------- | ------- | ---------- | ---------------------------- |
| 2021-04-05        | 0.1     | Yan        | Initial version created      |
|                   |         |            |                              |
|                   |         |            |                              | -->

![footer](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/zOMU1iwlZgwJXjWYzQAIgg/SNIBMfooter.png "footer")